name: Cypress Tests

on:
  workflow_dispatch:
        
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-actions@v2
        with:
          build: npm run build
          start: npm start
          
