name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - main
          - regressionBranch
        
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v5

        with:
          command: npx cypress run --record --key a0ad4936-d23a-4ef3-9290-7ec9da29c701
          Environment: ${{ inputs.environment }}
    
          
